# Generated by Django 4.1.3 on 2022-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first name', max_length=20)),
                ('last_name', models.CharField(help_text='last name', max_length=20)),
                ('user_email', models.EmailField(help_text='email', max_length=20)),
                ('education', models.TextField(help_text='Enter field documentation', max_length=50)),
                ('experience', models.TextField(help_text='Enter field documentation', max_length=50)),
                ('skills', models.TextField(help_text='Enter field documentation', max_length=50)),
                ('languages', models.CharField(help_text='Enter field documentation', max_length=40)),
            ],
        ),
    ]
