# Generated by Django 4.1.3 on 2022-12-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funny', '0003_form_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=20)),
                ('last_name', models.CharField(help_text='Last name', max_length=20)),
                ('user_email', models.EmailField(help_text='Email', max_length=20)),
                ('education', models.TextField(help_text='University', max_length=50)),
                ('experience', models.TextField(help_text='Professional experience', max_length=50)),
                ('skills', models.TextField(help_text='Skills', max_length=50)),
                ('languages', models.CharField(help_text='Foreign languages', max_length=40)),
                ('image', models.FileField(default='default.jpg', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
