# Generated by Django 4.1.3 on 2022-12-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funny', '0005_alter_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(help_text='University', max_length=300),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(help_text='Professional experience', max_length=300),
        ),
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(help_text='First name', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.CharField(help_text='Foreign languages', max_length=300),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(help_text='Last name', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(help_text='Skills', max_length=300),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user_email',
            field=models.EmailField(help_text='Email', max_length=120),
        ),
    ]
