# Generated by Django 4.1.3 on 2022-12-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funny', '0010_alter_resume_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='author',
            new_name='user',
        ),
    ]
