# Generated by Django 4.1.3 on 2022-12-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funny', '0011_rename_author_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
